### ISSUE TITLE
UglifyKeys.buildDir

### ISSUE THREAD

**Issue by ngsmithhotmailcom** [sbt/sbt-uglify#12]
is 
val appDir = SettingKey[File]("uglify-build-dir",) and 
val buildDir = SettingKey[File]("uglify-build-dir",)
supposed to have the same key name? ("uglify-build-dir")
Is this by design. 
I am having trouble getting control over my source and target directories

ngs

**Comment by jclyons** [comment]
I was wondering the same thing.

**Comment by objectmastery** [comment]
This could be fixed by making the key names different, but doing so causes UglifyJS to generate sourceMaps that reference files in `../app`.

Maybe `appDir` should just be removed and `buildDir` remain? Or even just remove both `appDir` and `buildDir` and use the value of `resourceManaged in uglify`?
